### ISSUE TITLE
出这种是怎么回事

### ISSUE THREAD

**Issue by wakanda-wq** [q164749/weixin#4]
Traceback (most recent call last):
  File "E:/新建文件夹 (4)/weixin-main(1)/weixin-main/main.py", line 148, in <module>
    weather, max_temperature, min_temperature = get_weather(province, city)
  File "E:/新建文件夹 (4)/weixin-main(1)/weixin-main/main.py", line 22, in get_weather
    city_id = cityinfo.cityInfo[province][city]["AREAID"]
KeyError: '石家庄'

**Comment by q164749** [comment]
省份有填写吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月14日(周日) 上午8:15
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [q164749/weixin] 出这种是怎么回事 (Issue #4)




 
Traceback (most recent call last):
 File "E:/新建文件夹 (4)/weixin-main(1)/weixin-main/main.py", line 148, in 
 weather, max_temperature, min_temperature = get_weather(province, city)
 File "E:/新建文件夹 (4)/weixin-main(1)/weixin-main/main.py", line 22, in get_weather
 city_id = cityinfo.cityInfo[province][city]["AREAID"]
 KeyError: '石家庄'

**Comment by wakanda-wq** [comment]
> 省份有填写吗
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年8月14日(周日) 上午8:15 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [q164749/weixin] 出这种是怎么回事 (Issue #4) Traceback (most recent call last): File "E:/新建文件夹 (4)/weixin-main(1)/weixin-main/main.py", line 148, in weather, max_temperature, min_temperature = get_weather(province, city) File "E:/新建文件夹 (4)/weixin-main(1)/weixin-main/main.py", line 22, in get_weather city_id = cityinfo.cityInfo[province][city]["AREAID"] KeyError: '石家庄' — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

感谢大佬，已经检查好，问题解决了
